name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Branch Tag
        id: branch_tag
        run: echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"
      - name: Build
        run: uv build
      - name: Create Release
        run: gh release create "${{ steps.branch_tag.outputs.tag }}" dist/* --title "${{ steps.branch_tag.outputs.tag }}" --notes "Please enter the content of the release here" --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
