name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Branch Tag
        id: branch_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: python -m pip install poetry==1.8.3
      - name: Build Poetry
        run: poetry build
      - name: Create Release
        run: gh release create "${{ steps.branch_tag.outputs.tag }}" dist/* --title "${{ steps.branch_tag.outputs.tag }}" --notes "Please enter the content of the release here" --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
